name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Version
        run: |
          export package_version="0.1.$((${{github.run_number}}-1))"
          echo "Package Version = $package_version"
          echo "package_version=$package_version" >> $GITHUB_ENV

      
      - name: Pack StaticSharp.StaticSharpSourceGenerator
        run: |
          dotnet pack ./Generator/StaticSharpSourceGenerator.csproj \
          -c Release \
          -p:PackageVersion=${{env.package_version}} \
          -o _out \
          -p:ContinuousIntegrationBuild=true \
          -p:PublishRepositoryUrl=true \
          -p:EmbedUntrackedSources=true \
          -p:DebugType=embedded
       
      - name: Publish StaticSharp.StaticSharpSourceGenerator
        run: |
          dotnet nuget push \
          ./_out/StaticSharp.StaticSharpSourceGenerator.${{env.package_version}}.nupkg \
          -k ${{secrets.NUGET_KEY}} \
          -s https://api.nuget.org/v3/index.json
        